// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/worksApi.proto

package go_micro_api_workApi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for WorkApi service

func NewWorkApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for WorkApi service

type WorkApiService interface {
	FindAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type workApiService struct {
	c    client.Client
	name string
}

func NewWorkApiService(name string, c client.Client) WorkApiService {
	return &workApiService{
		c:    c,
		name: name,
	}
}

func (c *workApiService) FindAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WorkApi.FindAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkApi service

type WorkApiHandler interface {
	FindAll(context.Context, *Request, *Response) error
}

func RegisterWorkApiHandler(s server.Server, hdlr WorkApiHandler, opts ...server.HandlerOption) error {
	type workApi interface {
		FindAll(ctx context.Context, in *Request, out *Response) error
	}
	type WorkApi struct {
		workApi
	}
	h := &workApiHandler{hdlr}
	return s.Handle(s.NewHandler(&WorkApi{h}, opts...))
}

type workApiHandler struct {
	WorkApiHandler
}

func (h *workApiHandler) FindAll(ctx context.Context, in *Request, out *Response) error {
	return h.WorkApiHandler.FindAll(ctx, in, out)
}
