// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/worksApi.proto

package worksApi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for WorksApi service

func NewWorksApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for WorksApi service

type WorksApiService interface {
	FindAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type worksApiService struct {
	c    client.Client
	name string
}

func NewWorksApiService(name string, c client.Client) WorksApiService {
	return &worksApiService{
		c:    c,
		name: name,
	}
}

func (c *worksApiService) FindAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WorksApi.FindAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorksApi service

type WorksApiHandler interface {
	FindAll(context.Context, *Request, *Response) error
}

func RegisterWorksApiHandler(s server.Server, hdlr WorksApiHandler, opts ...server.HandlerOption) error {
	type worksApi interface {
		FindAll(ctx context.Context, in *Request, out *Response) error
	}
	type WorksApi struct {
		worksApi
	}
	h := &worksApiHandler{hdlr}
	return s.Handle(s.NewHandler(&WorksApi{h}, opts...))
}

type worksApiHandler struct {
	WorksApiHandler
}

func (h *worksApiHandler) FindAll(ctx context.Context, in *Request, out *Response) error {
	return h.WorksApiHandler.FindAll(ctx, in, out)
}
